#!/usr/bin/env python3
"""
render_threat_model_schema.py — shared fragment IDs for the threat-model renderer.

Single source of truth for which fragments the template expects. Imported by
render_threat_model.py and by tests/test_render_threat_model.py so the resolver
and its tests stay in lockstep.

Fragment layout (canonical 11-section threat model report):

    00-header-metadata.md         required  metadata table
    00-toc.md                     generated by the resolver (heading scan)
    00b-changelog.md              optional  append-only assessment history
                                            (rendered when threat-model.yaml
                                            contains a non-empty changelog[])
    00-management-summary.md      required  executive summary
    01-system-overview.md         required  Section 1
    02-architecture.md            required  Section 2 (all 2.x subsections)
    03-use-cases.md               required  Section 3
    04-assets.md                  required  Section 4
    05-attack-surface.md          required  Section 5
    06-trust-boundaries.md        required  Section 6
    07-security-controls.md       required  Section 7
    07b-requirements-compliance   optional  Section 7b (only if requirements enabled)
    08-threat-register.md         required  Section 8
    09-critical-findings.md       required  Section 9
    10-mitigation-register.md     required  Section 10
    11-out-of-scope.md            required  Section 11

During Step 1 of the template migration, an additional transitional fragment
99-full-body.md is accepted as a pass-through for everything that hasn't been
split out yet. It gets removed once all 11 section fragments are migrated.

The 00b-changelog fragment is optional because a brand-new (first-run) full
assessment has nothing to render yet. It becomes mandatory-in-practice from
the second run onward once the changelog[] block in threat-model.yaml has at
least one entry.
"""

from __future__ import annotations


REQUIRED_FRAGMENTS: list[str] = [
    # Step 1 — MVP passthrough fragment, will be removed in later steps
    "99-full-body.md",
]

OPTIONAL_FRAGMENTS: list[str] = [
    "00b-changelog.md",
    "07b-requirements-compliance.md",
]

# Fragments the resolver produces itself (not written by agents).
GENERATED_FRAGMENTS: list[str] = [
    "00-toc.md",
]
