"""Tests for Patch P2 — Structural Determinism (A4 + A5 + A2).

Covers three orthogonal regressions:

    A4 — Mechanical structural fragments (`system-overview.md`,
         `architecture-diagrams.md`, `assets.md`, `attack-surface.md`,
         `out-of-scope.md`) are deterministically regenerated by the skill
         via `pregenerate_fragments.py --force --only ...`. The Phase 11
         LLM is no longer trusted to author these — any drift gets
         overwritten with the yaml-aligned canonical version.

    A5 — `gen_security_architecture(yaml_data, depth)` strips
         `<!-- NARRATIVE_PLACEHOLDER -->` comments from §7.4-§7.12 at
         quick depth so the LLM has no expansion bait there. §7.1, §7.2,
         §7.3 (with per-auth-method flow blocks), §7.13, §7.14 keep their
         placeholders since those are the high-value sections.

    A2 — `check_chain_tid_consistency` flags §3.1 chain-overview node
         labels that cite a T-NNN whose title in `threat-model.yaml`
         shares no content keyword with the label. Catches LLM-authored
         chain diagrams that reference completely the wrong threat.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent
_SCRIPTS = REPO_ROOT / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


pregen = _load_module("pregenerate_fragments",
                     _SCRIPTS / "pregenerate_fragments.py")
qa = _load_module("qa_checks", _SCRIPTS / "qa_checks.py")


def _minimal_yaml() -> dict:
    """Smallest yaml that lets the per-section generators run."""
    return {
        "meta": {"schema_version": 1, "plugin_version": "0.9.0-beta",
                 "analysis_version": 2, "git": {"commit_sha": "x"}},
        "project": {"name": "Test", "version": "1.0", "description": "x",
                    "author": "test", "license": "MIT", "repository": "x"},
        "components": [
            {"id": "C-01", "name": "Web", "kind": "service",
             "paths": ["src/"], "threat_ids": ["T-001"]},
        ],
        "threats": [
            {"t_id": "T-001", "component_id": "C-01",
             "stride": "Tampering",
             "title": "SQL injection in login route enables admin bypass",
             "scenario": "x", "risk": "Critical", "impact": "Critical",
             "cwe": "CWE-89"},
        ],
        "mitigations": [
            {"m_id": "M-001", "title": "Parameterise SQL", "priority": "P1",
             "effort": "Low", "addresses": ["T-001"]},
        ],
        "security_controls": [],
        "assets": [
            {"id": "A-001", "name": "User data", "classification": "Restricted",
             "description": "Users + hashed passwords."},
        ],
    }


# ---------------------------------------------------------------------------
# A4 — Mechanical fragments are force-regenerated
# ---------------------------------------------------------------------------

class TestForceOnlyOverwritesDriftedFragment:
    """A drifted fragment (e.g. LLM-authored without the ID column) gets
    cleanly overwritten by the canonical pre-generator output when the
    skill calls `--force --only`."""

    def test_force_overwrites_assets_drift(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        # Write a minimal yaml.
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))

        # Plant a "drifted" assets.md (4-col, no ID column) like the LLM
        # historically did.
        frag = out / ".fragments"
        frag.mkdir()
        (frag / "assets.md").write_text(
            "## 4. Assets\n\n"
            "| Asset | Classification | Description | Linked Threats |\n"
            "|---|---|---|---|\n"
            "| Drift | Public | drift content | F-001 |\n",
            encoding="utf-8",
        )

        # Without --force, idempotency keeps the drifted version.
        rc = pregen.main([str(out), "--only", "assets.md"])
        assert rc == 0
        text = (frag / "assets.md").read_text()
        assert "drift content" in text  # drifted version preserved

        # With --force, canonical pre-generator output replaces it.
        rc = pregen.main([str(out), "--force", "--only", "assets.md"])
        assert rc == 0
        text = (frag / "assets.md").read_text()
        assert "drift content" not in text          # drift overwritten
        assert "| Asset | ID | Classification" in text  # ID column restored
        assert "A-001" in text                       # canonical IDs present

    def test_force_only_does_not_touch_other_fragments(self, tmp_path: Path):
        """`--force --only assets.md` must NOT regenerate other fragments
        even if they exist on disk and would otherwise be force-overwritten
        in a `--force` (no `--only`) run."""
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))

        frag = out / ".fragments"
        frag.mkdir()
        # Custom system-overview that the skill should leave alone.
        (frag / "system-overview.md").write_text(
            "## 1. System Overview\n\nCUSTOM CONTENT — must survive --only assets.md.\n",
            encoding="utf-8",
        )
        rc = pregen.main([str(out), "--force", "--only", "assets.md"])
        assert rc == 0
        # system-overview is not touched.
        assert "CUSTOM CONTENT" in (frag / "system-overview.md").read_text()


# ---------------------------------------------------------------------------
# A5 — depth-aware §7 placeholder stripping
# ---------------------------------------------------------------------------

class TestSecurityArchitectureDepthAware:
    """`gen_security_architecture(yaml_data, depth)` emits fewer
    NARRATIVE_PLACEHOLDERs at quick depth — only the high-value sections
    (§7.1, §7.2, §7.3, §7.13, §7.14) keep their placeholders."""

    def test_quick_strips_more_placeholders_than_standard(self):
        ydata = _minimal_yaml()
        std = pregen.gen_security_architecture(ydata, depth="standard")
        quick = pregen.gen_security_architecture(ydata, depth="quick")
        n_std = std.count("NARRATIVE_PLACEHOLDER")
        n_quick = quick.count("NARRATIVE_PLACEHOLDER")
        assert n_quick < n_std, (
            f"quick must strip placeholders vs standard "
            f"(quick={n_quick}, standard={n_std})"
        )
        # Quick must keep §7.1, §7.2, §7.3 placeholders at minimum.
        assert "section=7.1" in quick or "domain=7.1" in quick \
            or "NARRATIVE_PLACEHOLDER: section=7.1" in quick
        assert "domain=KeyRisks" in quick           # §7.2
        assert "domain=7.3" in quick                # §7.3 narrative
        assert "domain=SecretMgmt" in quick         # §7.13
        assert "domain=DefenseInDepth" in quick     # §7.14

    def test_quick_strips_74_through_712_placeholders(self):
        """Specifically: §7.4-§7.12 NARRATIVE_PLACEHOLDERs must be absent
        at quick depth (no expansion bait for the LLM)."""
        ydata = _minimal_yaml()
        quick = pregen.gen_security_architecture(ydata, depth="quick")
        # The placeholder pattern is `domain=7.4` … `domain=7.12`.
        for n in ("7.4", "7.5", "7.6", "7.7", "7.10", "7.11", "7.12"):
            assert f"NARRATIVE_PLACEHOLDER: domain={n}" not in quick, (
                f"quick must strip §{n} NARRATIVE_PLACEHOLDER"
            )

    def test_standard_keeps_all_placeholders(self):
        """Sanity — standard depth retains the full set so the LLM has the
        expansion targets it expects at non-quick runs."""
        ydata = _minimal_yaml()
        std = pregen.gen_security_architecture(ydata, depth="standard")
        for n in ("7.4", "7.5", "7.6", "7.7", "7.10", "7.11", "7.12"):
            # At standard, each domain section emits its placeholder
            # unless the section is suppressed (§7.8 / §7.9 with no matches).
            if n not in ("7.8", "7.9"):
                assert f"NARRATIVE_PLACEHOLDER: domain={n}" in std

    def test_required_headings_emit_at_both_depths(self):
        """The contract requires §7.1-§7.12 + §7.13/§7.14 headings to exist
        regardless of depth. Quick mode strips placeholders but MUST NOT
        strip the heading itself or the contract gate fails."""
        ydata = _minimal_yaml()
        for depth in ("standard", "quick"):
            text = pregen.gen_security_architecture(ydata, depth=depth)
            for n, _title in pregen._SECARCH_SUBSECTIONS:
                if n in ("7.8", "7.9"):
                    # §7.8/§7.9 may render as "Not applicable" stub — heading
                    # still emits.
                    assert f"### {n}" in text, \
                        f"depth={depth}: §{n} heading must emit"
                else:
                    assert f"### {n}" in text, \
                        f"depth={depth}: §{n} heading must emit"


class TestPregenerateMainResolvesDepth:
    """`pregenerate_fragments.py` resolves depth from `--depth`,
    `.skill-config.json`, or default 'standard'."""

    def test_explicit_depth_flag_wins(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))
        # Write a config that would default to standard.
        (out / ".skill-config.json").write_text(
            json.dumps({"assessment_depth": "standard"}))
        # Explicit --depth quick overrides.
        rc = pregen.main([str(out), "--force", "--only", "security-architecture.md",
                          "--depth", "quick"])
        assert rc == 0
        text = (out / ".fragments" / "security-architecture.md").read_text()
        assert "NARRATIVE_PLACEHOLDER: domain=7.5" not in text  # stripped at quick

    def test_falls_back_to_skill_config(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))
        (out / ".skill-config.json").write_text(
            json.dumps({"assessment_depth": "quick"}))
        rc = pregen.main([str(out), "--force", "--only", "security-architecture.md"])
        assert rc == 0
        text = (out / ".fragments" / "security-architecture.md").read_text()
        assert "NARRATIVE_PLACEHOLDER: domain=7.5" not in text  # quick from config

    def test_defaults_to_standard_when_neither_set(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))
        rc = pregen.main([str(out), "--force", "--only", "security-architecture.md"])
        assert rc == 0
        text = (out / ".fragments" / "security-architecture.md").read_text()
        # Standard depth keeps the §7.5 placeholder.
        assert "NARRATIVE_PLACEHOLDER: domain=7.5" in text


# ---------------------------------------------------------------------------
# A2 — Chain T-ID consistency check
# ---------------------------------------------------------------------------

class TestChainTidConsistency:
    """Verify the keyword-overlap heuristic catches mislabeled chain diagrams
    while tolerating paraphrase."""

    def _build_md_with_chain(self, label: str) -> str:
        return (
            "# Threat Model — Test\n\n"
            "## 3. Attack Walkthroughs\n\n"
            "### 3.1 Attack Chain Overview\n\n"
            "#### Chain 1 — Test\n\n"
            "```mermaid\n"
            "graph LR\n"
            f"    A[\"{label}\"] --> B[Outcome]\n"
            "```\n\n"
            "**Key takeaway:** Test.\n"
        )

    def _build_yaml(self, t_title: str) -> dict:
        return {
            "meta": {"schema_version": 1},
            "threats": [{"t_id": "T-001", "title": t_title}],
        }

    def test_flag_when_label_keywords_disjoint_from_title(self, tmp_path: Path):
        """The 2026-05-07 regression: chain says 'T-001 SQL injection login'
        but T-001 is the RSA-key finding. Must be flagged."""
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(self._build_yaml(
            "Hardcoded RSA Private Key Enables Offline JWT Forgery"
        )))
        md = out / "threat-model.md"
        md.write_text(self._build_md_with_chain("T-001 SQL injection login endpoint"))
        report = qa.check_chain_tid_consistency(md, out)
        assert len(report.issues) == 1
        assert "T-001" in report.issues[0]
        assert report.ok == 0

    def test_pass_when_keywords_overlap_directly(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(self._build_yaml(
            "Hardcoded RSA Private Key in lib/insecurity.ts"
        )))
        md = out / "threat-model.md"
        md.write_text(self._build_md_with_chain("T-001 RSA key in insecurity.ts"))
        report = qa.check_chain_tid_consistency(md, out)
        assert report.issues == []
        assert report.ok == 1

    def test_pass_with_morphological_variation(self, tmp_path: Path):
        """Real REF case: label says 'MD5 hashes cracked in seconds';
        title says 'MD5 password hashing crackable via rainbow tables'.
        The shared roots 'crack' / 'hash' should match via prefix logic."""
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(self._build_yaml(
            "MD5 password hashing crackable via rainbow tables"
        )))
        md = out / "threat-model.md"
        md.write_text(self._build_md_with_chain("T-001 MD5 hashes cracked in seconds"))
        report = qa.check_chain_tid_consistency(md, out)
        assert report.issues == [], (
            f"morphological variation must not trip the check; got: "
            f"{report.issues}"
        )

    def test_skip_when_no_yaml(self, tmp_path: Path):
        """Legacy / pre-rendering: yaml absent → no-op pass."""
        out = tmp_path / "out"
        out.mkdir()
        md = out / "threat-model.md"
        md.write_text(self._build_md_with_chain("T-001 anything"))
        report = qa.check_chain_tid_consistency(md, out)
        assert report.issues == []
        assert report.ok == 1

    def test_skip_when_no_chain_overview(self, tmp_path: Path):
        """Quick-depth runs that omit §3.1 entirely → no-op pass."""
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(self._build_yaml("anything")))
        md = out / "threat-model.md"
        md.write_text("# Threat Model\n\n## 1. Overview\n\nNo §3.1 here.\n")
        report = qa.check_chain_tid_consistency(md, out)
        assert report.issues == []
        assert report.ok == 1

    def test_skip_when_label_has_no_content_keywords(self, tmp_path: Path):
        """A bare 'T-001' label with no descriptive text can't be validated
        — the check intentionally skips rather than false-flagging."""
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(self._build_yaml(
            "Hardcoded RSA Private Key in source"
        )))
        md = out / "threat-model.md"
        md.write_text(self._build_md_with_chain("T-001"))
        report = qa.check_chain_tid_consistency(md, out)
        assert report.issues == []
        assert report.ok == 1


class TestChainKeywordsOverlapHelper:
    """Unit-level checks on the prefix-matching logic."""

    def test_exact_match(self):
        assert qa._chain_keywords_overlap({"injection"}, {"injection"})

    def test_prefix_match(self):
        # "cracked" vs "crackable" share prefix "crack" (length 5).
        assert qa._chain_keywords_overlap({"cracked"}, {"crackable"})

    def test_substring_match(self):
        # "hash" ⊂ "hashing" — ≥ 4 chars on both sides.
        assert qa._chain_keywords_overlap({"hash"}, {"hashing"})

    def test_short_prefix_no_match(self):
        # "auth" (4 chars) vs "audit" (5 chars) share only 3 chars — no match
        # under the default min_prefix=5.
        assert not qa._chain_keywords_overlap({"auth"}, {"audit"})

    def test_no_overlap(self):
        assert not qa._chain_keywords_overlap(
            {"injection", "login"},
            {"forgery", "private", "rsa"},
        )


# ---------------------------------------------------------------------------
# Cross-cutting smoke — verify the skill flow A4+A5 work end-to-end
# ---------------------------------------------------------------------------

class TestP2EndToEndSmoke:
    """Re-run the pre-generator twice (mechanical force, scaffold idempotent)
    and verify both classes behave correctly."""

    def test_skill_flow_force_then_scaffold(self, tmp_path: Path):
        out = tmp_path / "out"
        out.mkdir()
        import yaml as _y
        (out / "threat-model.yaml").write_text(_y.dump(_minimal_yaml()))
        (out / ".skill-config.json").write_text(
            json.dumps({"assessment_depth": "quick"}))

        # Step 1 — pretend the LLM wrote a drifted security-architecture
        # narrative; the scaffold-only run must NOT overwrite it.
        frag = out / ".fragments"
        frag.mkdir()
        (frag / "security-architecture.md").write_text(
            "## 7. Security Architecture\n\nLLM-authored narrative, MUST survive.\n",
            encoding="utf-8",
        )

        # Mechanical fragments — force regenerate.
        rc = pregen.main([str(out), "--force",
                          "--only", "system-overview.md,architecture-diagrams.md,"
                                    "assets.md,attack-surface.md,out-of-scope.md"])
        assert rc == 0
        # All five mechanical fragments now exist with canonical content.
        for f in ("system-overview.md", "architecture-diagrams.md",
                  "assets.md", "attack-surface.md", "out-of-scope.md"):
            assert (frag / f).is_file(), f"{f} missing after --force"

        # security-architecture preserved (we didn't include it).
        sa = (frag / "security-architecture.md").read_text()
        assert "LLM-authored narrative, MUST survive" in sa, (
            "scaffold-only A4 path must NOT touch security-architecture.md")

        # Step 2 — scaffold-only run for security-architecture.md.
        # Idempotent (no --force) → existing LLM content preserved.
        rc = pregen.main([str(out), "--only", "security-architecture.md"])
        assert rc == 0
        sa = (frag / "security-architecture.md").read_text()
        assert "LLM-authored narrative, MUST survive" in sa, (
            "idempotent scaffold path must preserve existing content")
